name: MaxExSportsGRID
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41185
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1d1d'
    - '#ffffff'
    - '#000000'
    - '#d51919'
    - '#ba1414'
  brandStrength: 0.5
  lightness: 0.5499762753024697
  saturation: 0.21805427712388337
  rhythmicContrast: 0.5584791090805084
purpose: []
